name: Deploy

# Triggered on commits to the main branch.
on: 
  push:
    branches:
      - master

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: cd kusama-guide ; yarn ; yarn build ; node postprocess
        
      - name: Upload to IPFS
        uses: aquiladev/ipfs-action@v0.1.2
        with:
          path: ./kusama-guide/build
