name: Deploy Polkadot

# Triggered on commits to the main branch.
on: 
  push:
    branches:
      - master

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: yarn; yarn polkadot:build

      - name: Upload to IPFS
        uses: aquiladev/ipfs-action@v0.1.2
        with:
          path: ./polkadot-wiki/build/polkadot-wiki
